spring:
  application:
    name: Twitter-Clone

  datasource:
    url: jdbc:mysql://10.1.230.75:3306/USER_MANAGEMENT_DB
    username: Tariq
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  logging:
    level:
      org.springframework.jdbc: DEBUG
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql: TRACE
